version: '3.8'
services:
  postgres:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dbadmin
      - POSTGRES_DB=counter
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  word-counter:
    build:
      dockerfile: dockerfiles/server/Dockerfile
      context: ../
    environment:
      - WINDOW_DURATION=10
    ports:
      - 8000:8000
    depends_on:
      - postgres